## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(tidyverse)
library(lubridate)
library(mgcv)
library(gratia)
library(data.table)
library(rmarkdown)
library(kableExtra)
library(tidymv)
library(mgcViz)
library(ncdf4)  # Reading netCDF files (for chlorophyll-a data)
library(raster)  # Working with raster data (for chlorophyll-a data and bathymetry)