---
title: "Analysis report for the manuscript 'Temporal dynamics of the deep-sea pink sea urchin *Strongylocentrotus fragilis* on the Northeast Pacific continental margin'."
author: "Rylan J. Command"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
## target knits Rmds in their own session, so load libraries here.
source(here::here("packages.R"))
## if you want access to the functions you've written
lapply(list.files(here::here("./R"), full.names = TRUE), source)
```

```{r load-targets, include=FALSE}
# tar_load(c(target_1, target_2, target_3))
tar_load("urchin_model_summary_table")
# # If your chunk output is shown in-line, then you'll need to wrap tar_load()
# # like so:
# 
# withr::with_dir(here::here(), {
#   tar_load(c(target_1, target_2, target_3))
# })
# 
# # This is not needed when using tar_make() to render the document.
```

## Analysis
```{r table4, echo=FALSE}

kable(urchin_model_summary_table, booktabs = TRUE, col.names = NULL,
      caption = "Model summary table for parametric and smooth terms of final model.") %>% 
  kable_styling(full_width = FALSE) %>% 
  row_spec(1, bold = TRUE) %>% 
  row_spec(3, bold = TRUE)
```


## Reproducibility

<details><summary>Reproducibility receipt</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
